name: FTP Upload & Build

on:
  workflow_dispatch:

jobs:
  ftp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install zensical pyyaml

      - name: Build English docs
        run: |
          python hooks/script_deps.py docs
          zensical build --clean
          git checkout docs/

      - name: Build Swedish docs
        run: |
            zensical build --config-file zensical-sv.toml --clean

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./site/
          remote_path: /test
          sftp_only: true
